### ISSUE TITLE
OfficeMgmtCOM="True" implies you have SCCM

### ISSUE THREAD

**Issue by nayar34** [joaovitoriasilva/uninstall-office-msi-install-click-to-run#1]
This is great thank you so much!  One thing I noticed
In the InstallOffice.xml file you have this line:
OfficeMgmtCOM="True"
This makes the assumption that the end-user is deploying this with SCCM.  When you deploy and you don't have SCCM this creates a problem with Office ProPlus. When you install it will not allow you to get any updates it sets the updates to managed by System Administrators.  
I think the default for your script should be OfficeMgmtCOM="False" as more people are likely to be running them without having an SCCM infrastructure then not, and it isn't obvious that the update problem is caused by setting it to True.  Or make it clear in the readme that you need to change the line to False if you are not using SCCM.  Thanks!

**Comment by joaovitoriasilva** [comment]
Thank you for your feedback!
I will add this note to the README. But also note that I say that you should adapt the XML files to your needs.
